services:
  # Backend: FastAPI License Server
  - type: web
    name: ghostshell-license-server
    env: python
    region: oregon
    plan: free
    buildCommand: >-
      python3.12 -m pip install --upgrade pip setuptools wheel --no-cache-dir &&
      python3.12 -m pip install --no-cache-dir -r backend/requirements.txt --only-binary=:all: --no-deps ||
      python3.12 -m pip install --no-cache-dir -r backend/requirements.txt --only-binary=:all:
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DATABASE_URL
        fromDatabase:
          name: license_server_db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_TOKEN
        generateValue: true
      - key: UNIVERSAL_LICENSE_KEY
        value: GHOST-SHELL-UNIVERSAL-2025
      - key: PORT
        value: 10000

  # Frontend: Streamlit Admin Panel
  - type: web
    name: license-server-admin
    env: python
    region: oregon
    plan: free
    buildCommand: >-
      python3.12 -m pip install --upgrade pip setuptools wheel --no-cache-dir &&
      python3.12 -m pip install --no-cache-dir -r frontend/requirements-frontend.txt --only-binary=:all: --no-deps ||
      python3.12 -m pip install --no-cache-dir -r frontend/requirements-frontend.txt --only-binary=:all:
    startCommand: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: BACKEND_URL
        value: https://ghostshell-license-server.onrender.com

databases:
  - name: license_server_db
    databaseName: license_server_db
    user: license_server_db_user
    plan: free